### ISSUE TITLE
does not work with xelatex

### ISSUE THREAD

**Issue by tolot27** [u-fischer/putfenc#2]
Beside that `\DeclareUnicodeCharacter{2740}{Blume}` produces an error, the generated qr code does not contain the german umlauts anymore and the second gr code cannot be scanned with an Android 12 device.

How to fix it to get properly compiled with xelatex?

**Comment by u-fischer** [comment]
Well the package description says "A (virtual) fontencoding to enable with *pdflatex* ...". So why do you think that it should work with xelatex (or is even needed)? 

> Beside that \DeclareUnicodeCharacter{2740}{Blume} produces an error

Yes. But that is unrelated to the package. The command is not meant to be used with an unicode engine like xelatex.

**Comment by tolot27** [comment]
You are right. I could have asked: "How can the same be achieved for XeLaTeX?"

**Comment by u-fischer** [comment]
you could try this https://tex.stackexchange.com/a/516036/2388
